### ISSUE TITLE
No microphone input since Beta39 update

### ISSUE THREAD

**Issue by collingscreative** [xpilot-project/xpilot#139] opened 2022-12-05 17:28 UTC
Very possibly related to the latest change to get around the Mac OS asking for microphone permission.... just a note here, this is a designed safety feature and should never have been 'fixed'.

Now with the 39 beta, I get no microphone input (either external or built in to the laptop) on xPilot, whilst the microphone input works fine on other applications.

It's completely broken in 39. I have to downgrade back to 38 in order to use it.

Can you please reverse whatever has happened here? the OS alerting you that an application is requesting to use the microphone is a good thing!

**Comment by justinshannon** [comment] 2022-12-05 17:41
The latest change was not to "get around the Mac OS asking for microphone permission", it was to fix the issue with the user being asked _each time_ xPilot was launched to allow microphone access. The OS should only ask once and then remember.

I'm actively working on a fix; the problem is due to the application not being properly code signed with the correct entitlements.

**Comment by collingscreative** [comment] 2022-12-05 17:50
Ah I see, sorry I didn't realise that.

The constant request doesn't bother me, I'd even prefer it notifying me each time an application is requesting either camera or microphone usage.

Ah well. The only annoyance is the app keep telling me to upgrade but I understand why that is.

Thanks for the reply. Anything I can help with testing I'd be more than happy to.

**Comment by justinshannon** [comment] 2022-12-05 20:32
Can you give this version a try? http://xpilot-project.org/files/xPilot-2.0.0-beta.39-MacOS.zip

**Comment by collingscreative** [comment] 2022-12-05 20:42
Hi, yes this seems to work. Asked me to enable the microphone on first run.

Confirmed the sound level indicator shows up as I speak.

So I tried closing the app, and re-opening, and sound appears to be detected OK still.

Seems fine with my system, thanks for this.

**Comment by justinshannon** [comment] 2022-12-19 00:20
This issue is fixed in beta 40.

**Closed by justinshannon** 2022-12-19 00:20 UTC
