### ISSUE TITLE
Other planes bounce sharply during takeoff

### ISSUE THREAD

**Issue by AntonKuf** [xpilot-project/xpilot#151] opened 2023-02-13 18:49 UTC
after updating to beta 44, other planes bounce abruptly during takeoff

**Comment by justinshannon** [comment] 2023-02-13 18:57
Can you provide a video evidence of this? What version of X-Plane?

**Comment by AntonKuf** [comment] 2023-02-13 19:12
> Can you provide a video evidence of this? What version of X-Plane?

I will make a video tomorrow.  Xplane 12.03

**Comment by AntonKuf** [comment] 2023-02-14 08:44
> Can you provide a video evidence of this? What version of X-Plane?

https://youtu.be/_2jDc1YT6LM show video of this problem

**Comment by justinshannon** [comment] 2023-02-14 12:15
Does this happen with every aircraft at any airport?

**Comment by AntonKuf** [comment] 2023-02-14 12:18
> Does this happen with every aircraft at any airport?

Yes

**Comment by ogruetzmann** [comment] 2023-02-15 10:29
Can also confirm this. Also, saw a plane with a sharp nose down attitude during push, another one bouncing back/forward during taxi (think these two might be related).

**Comment by ogruetzmann** [comment] 2023-02-15 19:54
The opposite happens during landing

**Comment by justinshannon** [comment] 2023-02-17 01:17
Are you using real weather in X-Plane? I can only reproduce the altitude anomaly if I use manual weather, specifically if the altimeter setting is different than what it is in real life.

**Comment by ogruetzmann** [comment] 2023-02-17 01:28
I'm using real weather.

**Comment by justinshannon** [comment] 2023-02-17 01:50
What airport are you seeing this at? I observed at KBOS for about an hour and had no issues.

**Comment by ogruetzmann** [comment] 2023-02-17 02:01
I've been seeing it (I think) everywhere. EDDM for sure.
I'll go for a second install of x-plane to see what happens with a clean sim. I'm also still seeing planes at some odd levels (like 600 feet above/below) that should be x000 ft apart, so it might also be on my end.

**Comment by ogruetzmann** [comment] 2023-02-17 12:40
Unfortunately, the same thing happens with vanilla X-Plane (12.03 r01) with only xPilot and BB CSL installed. Used real weather and the values I got from X-Plane were the same I was expecting from the METAR.

For testing, I switched back to xPilot beta.43 and take offs/landings look normal again.

**Comment by ogruetzmann** [comment] 2023-02-17 13:53
Indeed, this is the case and also keeps aircraft on the ground when low pressure is present.
I manually set the pressure to 975 hPa / 28.79 inHg and watched aircraft staying on ground during take off or touch down way too early, so this effect works in both directions.

**Comment by justinshannon** [comment] 2023-02-17 23:41
I just released beta 45 that should hopefully fix this. Let me know if you're still seeing weirdness after updating.

**Comment by ogruetzmann** [comment] 2023-02-18 15:45
Still happening. I was spotting at VNKT this time, QNH 1021 and landing aircraft dropped onto the runway out of ~200-300 feet, which looks like the offset between QNH 1013 and 1021.
When playing with the local pressure, aircraft will be either high (high pressure) or low (low pressure) on the approach/departure.

It seems like this is the offset present in upper airspace as well, I was seeing similar values up there (like 700 feet above/below for traffic on levels 1000 feet above/below me). It more or less seems like the altitude correction is not applied at all, no matter if the traffic is within 6000 feet, but that observation might be wrong.

**Comment by justinshannon** [comment] 2023-02-23 04:25
Thanks to @ogruetzmann, this should be fixed in beta 46.

**Closed by justinshannon** 2023-02-23 04:25 UTC
